FROM fedora:23

RUN dnf install -y gcc-c++ clang libasan libubsan gnutls-devel hwloc hwloc-devel numactl-devel \
                           python3 libaio-devel ninja-build boost-devel git ragel xen-devel \
                           cryptopp-devel libpciaccess-devel libxml2-devel zlib-devel xfsprogs-devel
