FROM fedora:27

RUN dnf install -y \
    git \
    cmake \
    gcc-c++ \
    clang \
    ragel \
    ninja-build \
    python3 \
    gnutls-devel \
    hwloc \
    hwloc-devel \
    numactl-devel \
    boost-devel \
    cryptopp-devel \
    zlib-devel \
    xfsprogs-devel \
    lz4-devel \
    systemtap-sdt-devel \
    protobuf-compiler \
    protobuf-devel \
    lksctp-tools-devel \
    yaml-cpp-devel \
    libasan \
    libubsan \
    libunwind-devel \
    libaio-devel \
    libpciaccess-devel \
    libxml2-devel
