# Created by and for Qt Creator This file was created for editing the project sources only.
# You may attempt to use it for building too, by modifying this file here.

#TARGET = db_simple

QT = core gui widgets

HEADERS = \
   $$PWD/apps/lib/stop_signal.hh \
   $$PWD/apps/memcached/memcached.hh \
   $$PWD/build/debug/apps/httpd/demo.json.hh \
   $$PWD/build/debug/apps/memcached/ascii.hh \
   $$PWD/build/debug/gen/include/seastar/http/chunk_parsers.hh \
   $$PWD/build/debug/gen/include/seastar/http/request_parser.hh \
   $$PWD/build/debug/gen/include/seastar/http/response_parser.hh \
   $$PWD/build/debug/gen/src/proto/metrics2.pb.h \
   $$PWD/build/release/apps/httpd/demo.json.hh \
   $$PWD/build/release/apps/memcached/ascii.hh \
   $$PWD/build/release/gen/include/seastar/http/chunk_parsers.hh \
   $$PWD/build/release/gen/include/seastar/http/request_parser.hh \
   $$PWD/build/release/gen/include/seastar/http/response_parser.hh \
   $$PWD/build/release/gen/src/proto/metrics2.pb.h \
   $$PWD/build2/apps/httpd/demo.json.hh \
   $$PWD/build2/apps/memcached/ascii.hh \
   $$PWD/build2/gen/include/seastar/http/chunk_parsers.hh \
   $$PWD/build2/gen/include/seastar/http/request_parser.hh \
   $$PWD/build2/gen/include/seastar/http/response_parser.hh \
   $$PWD/build2/gen/src/proto/metrics2.pb.h \
   $$PWD/demos/tls_echo_server.hh \
   $$PWD/include/seastar/core/internal/api-level.hh \
   $$PWD/include/seastar/core/internal/buffer_allocator.hh \
   $$PWD/include/seastar/core/internal/estimated_histogram.hh \
   $$PWD/include/seastar/core/internal/io_desc.hh \
   $$PWD/include/seastar/core/internal/io_intent.hh \
   $$PWD/include/seastar/core/internal/io_request.hh \
   $$PWD/include/seastar/core/internal/io_sink.hh \
   $$PWD/include/seastar/core/internal/poll.hh \
   $$PWD/include/seastar/core/internal/pollable_fd.hh \
   $$PWD/include/seastar/core/internal/read_state.hh \
   $$PWD/include/seastar/core/internal/run_in_background.hh \
   $$PWD/include/seastar/core/internal/stall_detector.hh \
   $$PWD/include/seastar/core/internal/uname.hh \
   $$PWD/include/seastar/core/abort_on_ebadf.hh \
   $$PWD/include/seastar/core/abort_on_expiry.hh \
   $$PWD/include/seastar/core/abort_source.hh \
   $$PWD/include/seastar/core/abortable_fifo.hh \
   $$PWD/include/seastar/core/alien.hh \
   $$PWD/include/seastar/core/align.hh \
   $$PWD/include/seastar/core/aligned_buffer.hh \
   $$PWD/include/seastar/core/app-template.hh \
   $$PWD/include/seastar/core/array_map.hh \
   $$PWD/include/seastar/core/bitops.hh \
   $$PWD/include/seastar/core/bitset-iter.hh \
   $$PWD/include/seastar/core/byteorder.hh \
   $$PWD/include/seastar/core/cacheline.hh \
   $$PWD/include/seastar/core/checked_ptr.hh \
   $$PWD/include/seastar/core/chunked_fifo.hh \
   $$PWD/include/seastar/core/circular_buffer.hh \
   $$PWD/include/seastar/core/circular_buffer_fixed_capacity.hh \
   $$PWD/include/seastar/core/condition-variable.hh \
   $$PWD/include/seastar/core/coroutine.hh \
   $$PWD/include/seastar/core/deleter.hh \
   $$PWD/include/seastar/core/distributed.hh \
   $$PWD/include/seastar/core/do_with.hh \
   $$PWD/include/seastar/core/dpdk_rte.hh \
   $$PWD/include/seastar/core/enum.hh \
   $$PWD/include/seastar/core/exception_hacks.hh \
   $$PWD/include/seastar/core/execution_stage.hh \
   $$PWD/include/seastar/core/expiring_fifo.hh \
   $$PWD/include/seastar/core/fair_queue.hh \
   $$PWD/include/seastar/core/file-types.hh \
   $$PWD/include/seastar/core/file.hh \
   $$PWD/include/seastar/core/fsnotify.hh \
   $$PWD/include/seastar/core/fsqual.hh \
   $$PWD/include/seastar/core/fstream.hh \
   $$PWD/include/seastar/core/function_traits.hh \
   $$PWD/include/seastar/core/future-util.hh \
   $$PWD/include/seastar/core/future.hh \
   $$PWD/include/seastar/core/gate.hh \
   $$PWD/include/seastar/core/idle_cpu_handler.hh \
   $$PWD/include/seastar/core/io_intent.hh \
   $$PWD/include/seastar/core/io_priority_class.hh \
   $$PWD/include/seastar/core/io_queue.hh \
   $$PWD/include/seastar/core/iostream-impl.hh \
   $$PWD/include/seastar/core/iostream.hh \
   $$PWD/include/seastar/core/layered_file.hh \
   $$PWD/include/seastar/core/linux-aio.hh \
   $$PWD/include/seastar/core/loop.hh \
   $$PWD/include/seastar/core/lowres_clock.hh \
   $$PWD/include/seastar/core/make_task.hh \
   $$PWD/include/seastar/core/manual_clock.hh \
   $$PWD/include/seastar/core/map_reduce.hh \
   $$PWD/include/seastar/core/memory.hh \
   $$PWD/include/seastar/core/metrics.hh \
   $$PWD/include/seastar/core/metrics_api.hh \
   $$PWD/include/seastar/core/metrics_registration.hh \
   $$PWD/include/seastar/core/metrics_types.hh \
   $$PWD/include/seastar/core/on_internal_error.hh \
   $$PWD/include/seastar/core/pipe.hh \
   $$PWD/include/seastar/core/polymorphic_temporary_buffer.hh \
   $$PWD/include/seastar/core/posix.hh \
   $$PWD/include/seastar/core/preempt.hh \
   $$PWD/include/seastar/core/prefetch.hh \
   $$PWD/include/seastar/core/print.hh \
   $$PWD/include/seastar/core/prometheus.hh \
   $$PWD/include/seastar/core/queue.hh \
   $$PWD/include/seastar/core/ragel.hh \
   $$PWD/include/seastar/core/reactor.hh \
   $$PWD/include/seastar/core/reactor_config.hh \
   $$PWD/include/seastar/core/relabel_config.hh \
   $$PWD/include/seastar/core/report_exception.hh \
   $$PWD/include/seastar/core/resource.hh \
   $$PWD/include/seastar/core/rwlock.hh \
   $$PWD/include/seastar/core/scattered_message.hh \
   $$PWD/include/seastar/core/scheduling.hh \
   $$PWD/include/seastar/core/scheduling_specific.hh \
   $$PWD/include/seastar/core/scollectd.hh \
   $$PWD/include/seastar/core/scollectd_api.hh \
   $$PWD/include/seastar/core/seastar.hh \
   $$PWD/include/seastar/core/semaphore.hh \
   $$PWD/include/seastar/core/shard_id.hh \
   $$PWD/include/seastar/core/sharded.hh \
   $$PWD/include/seastar/core/shared_future.hh \
   $$PWD/include/seastar/core/shared_mutex.hh \
   $$PWD/include/seastar/core/shared_ptr.hh \
   $$PWD/include/seastar/core/shared_ptr_debug_helper.hh \
   $$PWD/include/seastar/core/shared_ptr_incomplete.hh \
   $$PWD/include/seastar/core/simple-stream.hh \
   $$PWD/include/seastar/core/slab.hh \
   $$PWD/include/seastar/core/sleep.hh \
   $$PWD/include/seastar/core/smp.hh \
   $$PWD/include/seastar/core/smp_options.hh \
   $$PWD/include/seastar/core/sstring.hh \
   $$PWD/include/seastar/core/stall_sampler.hh \
   $$PWD/include/seastar/core/stream.hh \
   $$PWD/include/seastar/core/systemwide_memory_barrier.hh \
   $$PWD/include/seastar/core/task.hh \
   $$PWD/include/seastar/core/temporary_buffer.hh \
   $$PWD/include/seastar/core/thread.hh \
   $$PWD/include/seastar/core/thread_cputime_clock.hh \
   $$PWD/include/seastar/core/thread_impl.hh \
   $$PWD/include/seastar/core/timed_out_error.hh \
   $$PWD/include/seastar/core/timer-set.hh \
   $$PWD/include/seastar/core/timer.hh \
   $$PWD/include/seastar/core/transfer.hh \
   $$PWD/include/seastar/core/unaligned.hh \
   $$PWD/include/seastar/core/units.hh \
   $$PWD/include/seastar/core/vector-data-sink.hh \
   $$PWD/include/seastar/core/weak_ptr.hh \
   $$PWD/include/seastar/core/when_all.hh \
   $$PWD/include/seastar/core/when_any.hh \
   $$PWD/include/seastar/core/with_scheduling_group.hh \
   $$PWD/include/seastar/core/with_timeout.hh \
   $$PWD/include/seastar/coroutine/all.hh \
   $$PWD/include/seastar/coroutine/as_future.hh \
   $$PWD/include/seastar/coroutine/exception.hh \
   $$PWD/include/seastar/coroutine/generator.hh \
   $$PWD/include/seastar/coroutine/maybe_yield.hh \
   $$PWD/include/seastar/coroutine/parallel_for_each.hh \
   $$PWD/include/seastar/coroutine/switch_to.hh \
   $$PWD/include/seastar/http/internal/content_source.hh \
   $$PWD/include/seastar/http/api_docs.hh \
   $$PWD/include/seastar/http/client.hh \
   $$PWD/include/seastar/http/common.hh \
   $$PWD/include/seastar/http/exception.hh \
   $$PWD/include/seastar/http/file_handler.hh \
   $$PWD/include/seastar/http/function_handlers.hh \
   $$PWD/include/seastar/http/handlers.hh \
   $$PWD/include/seastar/http/httpd.hh \
   $$PWD/include/seastar/http/json_path.hh \
   $$PWD/include/seastar/http/matcher.hh \
   $$PWD/include/seastar/http/matchrules.hh \
   $$PWD/include/seastar/http/mime_types.hh \
   $$PWD/include/seastar/http/reply.hh \
   $$PWD/include/seastar/http/request.hh \
   $$PWD/include/seastar/http/routes.hh \
   $$PWD/include/seastar/http/short_streams.hh \
   $$PWD/include/seastar/http/transformers.hh \
   $$PWD/include/seastar/http/url.hh \
   $$PWD/include/seastar/json/formatter.hh \
   $$PWD/include/seastar/json/json_elements.hh \
   $$PWD/include/seastar/net/api.hh \
   $$PWD/include/seastar/net/arp.hh \
   $$PWD/include/seastar/net/byteorder.hh \
   $$PWD/include/seastar/net/config.hh \
   $$PWD/include/seastar/net/const.hh \
   $$PWD/include/seastar/net/dhcp.hh \
   $$PWD/include/seastar/net/dns.hh \
   $$PWD/include/seastar/net/dpdk.hh \
   $$PWD/include/seastar/net/ethernet.hh \
   $$PWD/include/seastar/net/inet_address.hh \
   $$PWD/include/seastar/net/ip.hh \
   $$PWD/include/seastar/net/ip_checksum.hh \
   $$PWD/include/seastar/net/ipv4_address.hh \
   $$PWD/include/seastar/net/ipv6_address.hh \
   $$PWD/include/seastar/net/native-stack.hh \
   $$PWD/include/seastar/net/net.hh \
   $$PWD/include/seastar/net/packet-data-source.hh \
   $$PWD/include/seastar/net/packet-util.hh \
   $$PWD/include/seastar/net/packet.hh \
   $$PWD/include/seastar/net/posix-stack.hh \
   $$PWD/include/seastar/net/proxy.hh \
   $$PWD/include/seastar/net/socket_defs.hh \
   $$PWD/include/seastar/net/stack.hh \
   $$PWD/include/seastar/net/tcp-stack.hh \
   $$PWD/include/seastar/net/tcp.hh \
   $$PWD/include/seastar/net/tls.hh \
   $$PWD/include/seastar/net/toeplitz.hh \
   $$PWD/include/seastar/net/udp.hh \
   $$PWD/include/seastar/net/unix_address.hh \
   $$PWD/include/seastar/net/virtio-interface.hh \
   $$PWD/include/seastar/net/virtio.hh \
   $$PWD/include/seastar/rpc/lz4_compressor.hh \
   $$PWD/include/seastar/rpc/lz4_fragmented_compressor.hh \
   $$PWD/include/seastar/rpc/multi_algo_compressor_factory.hh \
   $$PWD/include/seastar/rpc/rpc.hh \
   $$PWD/include/seastar/rpc/rpc_impl.hh \
   $$PWD/include/seastar/rpc/rpc_types.hh \
   $$PWD/include/seastar/testing/entry_point.hh \
   $$PWD/include/seastar/testing/exchanger.hh \
   $$PWD/include/seastar/testing/linux_perf_event.hh \
   $$PWD/include/seastar/testing/on_internal_error.hh \
   $$PWD/include/seastar/testing/perf_tests.hh \
   $$PWD/include/seastar/testing/random.hh \
   $$PWD/include/seastar/testing/seastar_test.hh \
   $$PWD/include/seastar/testing/test_case.hh \
   $$PWD/include/seastar/testing/test_runner.hh \
   $$PWD/include/seastar/testing/thread_test_case.hh \
   $$PWD/include/seastar/util/internal/iovec_utils.hh \
   $$PWD/include/seastar/util/internal/magic.hh \
   $$PWD/include/seastar/util/alloc_failure_injector.hh \
   $$PWD/include/seastar/util/backtrace.hh \
   $$PWD/include/seastar/util/bool_class.hh \
   $$PWD/include/seastar/util/closeable.hh \
   $$PWD/include/seastar/util/concepts.hh \
   $$PWD/include/seastar/util/conversions.hh \
   $$PWD/include/seastar/util/critical_alloc_section.hh \
   $$PWD/include/seastar/util/defer.hh \
   $$PWD/include/seastar/util/eclipse.hh \
   $$PWD/include/seastar/util/exceptions.hh \
   $$PWD/include/seastar/util/file.hh \
   $$PWD/include/seastar/util/function_input_iterator.hh \
   $$PWD/include/seastar/util/indirect.hh \
   $$PWD/include/seastar/util/is_smart_ptr.hh \
   $$PWD/include/seastar/util/later.hh \
   $$PWD/include/seastar/util/lazy.hh \
   $$PWD/include/seastar/util/log-cli.hh \
   $$PWD/include/seastar/util/log-impl.hh \
   $$PWD/include/seastar/util/log.hh \
   $$PWD/include/seastar/util/memory_diagnostics.hh \
   $$PWD/include/seastar/util/modules.hh \
   $$PWD/include/seastar/util/noncopyable_function.hh \
   $$PWD/include/seastar/util/optimized_optional.hh \
   $$PWD/include/seastar/util/print_safe.hh \
   $$PWD/include/seastar/util/process.hh \
   $$PWD/include/seastar/util/program-options.hh \
   $$PWD/include/seastar/util/read_first_line.hh \
   $$PWD/include/seastar/util/reference_wrapper.hh \
   $$PWD/include/seastar/util/sampler.hh \
   $$PWD/include/seastar/util/shared_token_bucket.hh \
   $$PWD/include/seastar/util/short_streams.hh \
   $$PWD/include/seastar/util/source_location-compat.hh \
   $$PWD/include/seastar/util/spinlock.hh \
   $$PWD/include/seastar/util/std-compat.hh \
   $$PWD/include/seastar/util/string_utils.hh \
   $$PWD/include/seastar/util/tmp_file.hh \
   $$PWD/include/seastar/util/transform_iterator.hh \
   $$PWD/include/seastar/util/tuple_utils.hh \
   $$PWD/include/seastar/util/used_size.hh \
   $$PWD/include/seastar/util/variant_utils.hh \
   $$PWD/include/seastar/websocket/server.hh \
   $$PWD/src/core/cgroup.hh \
   $$PWD/src/core/file-impl.hh \
   $$PWD/src/core/prefault.hh \
   $$PWD/src/core/program_options.hh \
   $$PWD/src/core/reactor_backend.hh \
   $$PWD/src/core/scollectd-impl.hh \
   $$PWD/src/core/syscall_result.hh \
   $$PWD/src/core/syscall_work_queue.hh \
   $$PWD/src/core/thread_pool.hh \
   $$PWD/src/core/vla.hh \
   $$PWD/src/net/native-stack-impl.hh \
   $$PWD/tests/unit/loopback_socket.hh \
   $$PWD/tests/unit/mock_file.hh \
   $$PWD/tests/unit/tl-generator.hh \
   $$PWD/tests/unit/tmpdir.hh

SOURCES = \
   $$PWD/apps/httpd/main.cc \
   $$PWD/apps/io_tester/io_tester.cc \
   $$PWD/apps/io_tester/ioinfo.cc \
   $$PWD/apps/iotune/iotune.cc \
   $$PWD/apps/memcached/tests/test_ascii_parser.cc \
   $$PWD/apps/memcached/memcache.cc \
   $$PWD/apps/metrics_tester/metrics_tester.cc \
   $$PWD/apps/rpc_tester/rpc_tester.cc \
   $$PWD/apps/seawreck/seawreck.cc \
   $$PWD/build/debug/apps/httpd/demo.json.cc \
   $$PWD/build/debug/CMakeFiles/3.22.1/CompilerIdCXX/CMakeCXXCompilerId.cpp \
   $$PWD/build/debug/CMakeFiles/CheckFunctionExists/CheckFunctionExists.cxx \
   $$PWD/build/debug/gen/src/proto/metrics2.pb.cc \
   $$PWD/build/release/apps/httpd/demo.json.cc \
   $$PWD/build/release/CMakeFiles/3.22.1/CompilerIdCXX/CMakeCXXCompilerId.cpp \
   $$PWD/build/release/CMakeFiles/CheckFunctionExists/CheckFunctionExists.cxx \
   $$PWD/build/release/gen/src/proto/metrics2.pb.cc \
   $$PWD/build2/apps/httpd/demo.json.cc \
   $$PWD/build2/CMakeFiles/3.22.1/CompilerIdCXX/CMakeCXXCompilerId.cpp \
   $$PWD/build2/CMakeFiles/CheckFunctionExists/CheckFunctionExists.cxx \
   $$PWD/build2/gen/src/proto/metrics2.pb.cc \
   $$PWD/cmake/code_tests/LinuxMembarrier_test.cc \
   $$PWD/cmake/code_tests/rt_test.cc \
   $$PWD/cmake/code_tests/Sanitizers_fiber_test.cc \
   $$PWD/cmake/code_tests/Source_location_default_argument.cc \
   $$PWD/cmake/code_tests/Source_location_test.cc \
   $$PWD/cmake/code_tests/stdout_test.cc \
   $$PWD/demos/block_discard_demo.cc \
   $$PWD/demos/coroutines_demo.cc \
   $$PWD/demos/db_demo.cc \
   $$PWD/demos/echo_demo.cc \
   $$PWD/demos/file_demo.cc \
   $$PWD/demos/hello-cxx-module.cc \
   $$PWD/demos/hello-world.cc \
   $$PWD/demos/http_client_demo.cc \
   $$PWD/demos/ip_demo.cc \
   $$PWD/demos/l3_demo.cc \
   $$PWD/demos/line_count_demo.cc \
   $$PWD/demos/rpc_demo.cc \
   $$PWD/demos/scheduling_group_demo.cc \
   $$PWD/demos/sharded_parameter_demo.cc \
   $$PWD/demos/tcp_demo.cc \
   $$PWD/demos/tcp_sctp_client_demo.cc \
   $$PWD/demos/tcp_sctp_server_demo.cc \
   $$PWD/demos/tls_echo_server_demo.cc \
   $$PWD/demos/tls_simple_client_demo.cc \
   $$PWD/demos/tutorial_examples.cc \
   $$PWD/demos/udp_client_demo.cc \
   $$PWD/demos/udp_server_demo.cc \
   $$PWD/demos/udp_zero_copy_demo.cc \
   $$PWD/demos/websocket_demo.cc \
   $$PWD/src/core/alien.cc \
   $$PWD/src/core/app-template.cc \
   $$PWD/src/core/condition-variable.cc \
   $$PWD/src/core/dpdk_rte.cc \
   $$PWD/src/core/exception_hacks.cc \
   $$PWD/src/core/execution_stage.cc \
   $$PWD/src/core/fair_queue.cc \
   $$PWD/src/core/file.cc \
   $$PWD/src/core/fsnotify.cc \
   $$PWD/src/core/fsqual.cc \
   $$PWD/src/core/fstream.cc \
   $$PWD/src/core/future-util.cc \
   $$PWD/src/core/future.cc \
   $$PWD/src/core/io_queue.cc \
   $$PWD/src/core/linux-aio.cc \
   $$PWD/src/core/memory.cc \
   $$PWD/src/core/metrics.cc \
   $$PWD/src/core/on_internal_error.cc \
   $$PWD/src/core/posix.cc \
   $$PWD/src/core/program_options.cc \
   $$PWD/src/core/prometheus.cc \
   $$PWD/src/core/reactor.cc \
   $$PWD/src/core/reactor_backend.cc \
   $$PWD/src/core/resource.cc \
   $$PWD/src/core/scollectd.cc \
   $$PWD/src/core/semaphore.cc \
   $$PWD/src/core/sharded.cc \
   $$PWD/src/core/smp.cc \
   $$PWD/src/core/sstring.cc \
   $$PWD/src/core/systemwide_memory_barrier.cc \
   $$PWD/src/core/thread.cc \
   $$PWD/src/core/thread_pool.cc \
   $$PWD/src/core/uname.cc \
   $$PWD/src/http/api_docs.cc \
   $$PWD/src/http/client.cc \
   $$PWD/src/http/common.cc \
   $$PWD/src/http/file_handler.cc \
   $$PWD/src/http/httpd.cc \
   $$PWD/src/http/json_path.cc \
   $$PWD/src/http/matcher.cc \
   $$PWD/src/http/mime_types.cc \
   $$PWD/src/http/reply.cc \
   $$PWD/src/http/request.cc \
   $$PWD/src/http/routes.cc \
   $$PWD/src/http/transformers.cc \
   $$PWD/src/http/url.cc \
   $$PWD/src/json/formatter.cc \
   $$PWD/src/json/json_elements.cc \
   $$PWD/src/net/arp.cc \
   $$PWD/src/net/config.cc \
   $$PWD/src/net/dhcp.cc \
   $$PWD/src/net/dns.cc \
   $$PWD/src/net/dpdk.cc \
   $$PWD/src/net/ethernet.cc \
   $$PWD/src/net/inet_address.cc \
   $$PWD/src/net/ip.cc \
   $$PWD/src/net/ip_checksum.cc \
   $$PWD/src/net/native-stack.cc \
   $$PWD/src/net/net.cc \
   $$PWD/src/net/packet.cc \
   $$PWD/src/net/posix-stack.cc \
   $$PWD/src/net/proxy.cc \
   $$PWD/src/net/socket_address.cc \
   $$PWD/src/net/stack.cc \
   $$PWD/src/net/tcp.cc \
   $$PWD/src/net/tls.cc \
   $$PWD/src/net/udp.cc \
   $$PWD/src/net/unix_address.cc \
   $$PWD/src/net/virtio.cc \
   $$PWD/src/rpc/lz4_compressor.cc \
   $$PWD/src/rpc/lz4_fragmented_compressor.cc \
   $$PWD/src/rpc/rpc.cc \
   $$PWD/src/testing/entry_point.cc \
   $$PWD/src/testing/random.cc \
   $$PWD/src/testing/seastar_test.cc \
   $$PWD/src/testing/test_runner.cc \
   $$PWD/src/util/alloc_failure_injector.cc \
   $$PWD/src/util/backtrace.cc \
   $$PWD/src/util/conversions.cc \
   $$PWD/src/util/exceptions.cc \
   $$PWD/src/util/file.cc \
   $$PWD/src/util/log.cc \
   $$PWD/src/util/process.cc \
   $$PWD/src/util/program-options.cc \
   $$PWD/src/util/read_first_line.cc \
   $$PWD/src/util/short_streams.cc \
   $$PWD/src/util/tmp_file.cc \
   $$PWD/src/websocket/server.cc \
   $$PWD/src/seastar.cc \
   $$PWD/tests/perf/allocator_perf.cc \
   $$PWD/tests/perf/coroutine_perf.cc \
   $$PWD/tests/perf/fair_queue_perf.cc \
   $$PWD/tests/perf/fstream_perf.cc \
   $$PWD/tests/perf/future_util_perf.cc \
   $$PWD/tests/perf/linux_perf_event.cc \
   $$PWD/tests/perf/perf_tests.cc \
   $$PWD/tests/perf/rpc_perf.cc \
   $$PWD/tests/perf/shared_token_bucket.cc \
   $$PWD/tests/perf/smp_submit_to_perf.cc \
   $$PWD/tests/unit/abort_source_test.cc \
   $$PWD/tests/unit/abortable_fifo_test.cc \
   $$PWD/tests/unit/alien_test.cc \
   $$PWD/tests/unit/alloc_test.cc \
   $$PWD/tests/unit/allocator_test.cc \
   $$PWD/tests/unit/app-template_test.cc \
   $$PWD/tests/unit/checked_ptr_test.cc \
   $$PWD/tests/unit/chunk_parsers_test.cc \
   $$PWD/tests/unit/chunked_fifo_test.cc \
   $$PWD/tests/unit/circular_buffer_fixed_capacity_test.cc \
   $$PWD/tests/unit/circular_buffer_test.cc \
   $$PWD/tests/unit/closeable_test.cc \
   $$PWD/tests/unit/condition_variable_test.cc \
   $$PWD/tests/unit/connect_test.cc \
   $$PWD/tests/unit/content_source_test.cc \
   $$PWD/tests/unit/coroutines_test.cc \
   $$PWD/tests/unit/defer_test.cc \
   $$PWD/tests/unit/deleter_test.cc \
   $$PWD/tests/unit/directory_test.cc \
   $$PWD/tests/unit/distributed_test.cc \
   $$PWD/tests/unit/dns_test.cc \
   $$PWD/tests/unit/exception_logging_test.cc \
   $$PWD/tests/unit/execution_stage_test.cc \
   $$PWD/tests/unit/expiring_fifo_test.cc \
   $$PWD/tests/unit/fair_queue_test.cc \
   $$PWD/tests/unit/file_io_test.cc \
   $$PWD/tests/unit/file_utils_test.cc \
   $$PWD/tests/unit/foreign_ptr_test.cc \
   $$PWD/tests/unit/fsnotifier_test.cc \
   $$PWD/tests/unit/fstream_test.cc \
   $$PWD/tests/unit/futures_test.cc \
   $$PWD/tests/unit/httpd_test.cc \
   $$PWD/tests/unit/io_queue_test.cc \
   $$PWD/tests/unit/ipv6_test.cc \
   $$PWD/tests/unit/json_formatter_test.cc \
   $$PWD/tests/unit/locking_test.cc \
   $$PWD/tests/unit/log_buf_test.cc \
   $$PWD/tests/unit/lowres_clock_test.cc \
   $$PWD/tests/unit/metrics_test.cc \
   $$PWD/tests/unit/net_config_test.cc \
   $$PWD/tests/unit/network_interface_test.cc \
   $$PWD/tests/unit/noncopyable_function_test.cc \
   $$PWD/tests/unit/output_stream_test.cc \
   $$PWD/tests/unit/packet_test.cc \
   $$PWD/tests/unit/pipe_test.cc \
   $$PWD/tests/unit/program_options_test.cc \
   $$PWD/tests/unit/queue_test.cc \
   $$PWD/tests/unit/request_parser_test.cc \
   $$PWD/tests/unit/rpc_test.cc \
   $$PWD/tests/unit/scheduling_group_test.cc \
   $$PWD/tests/unit/semaphore_test.cc \
   $$PWD/tests/unit/sharded_test.cc \
   $$PWD/tests/unit/shared_ptr_test.cc \
   $$PWD/tests/unit/shared_token_bucket_test.cc \
   $$PWD/tests/unit/signal_test.cc \
   $$PWD/tests/unit/simple_stream_test.cc \
   $$PWD/tests/unit/slab_test.cc \
   $$PWD/tests/unit/smp_test.cc \
   $$PWD/tests/unit/socket_test.cc \
   $$PWD/tests/unit/source_location_test.cc \
   $$PWD/tests/unit/spawn_test.cc \
   $$PWD/tests/unit/sstring_test.cc \
   $$PWD/tests/unit/stall_detector_test.cc \
   $$PWD/tests/unit/stream_reader_test.cc \
   $$PWD/tests/unit/thread_context_switch_test.cc \
   $$PWD/tests/unit/thread_test.cc \
   $$PWD/tests/unit/timer_test.cc \
   $$PWD/tests/unit/tls_test.cc \
   $$PWD/tests/unit/tuple_utils_test.cc \
   $$PWD/tests/unit/uname_test.cc \
   $$PWD/tests/unit/unix_domain_test.cc \
   $$PWD/tests/unit/unwind_test.cc \
   $$PWD/tests/unit/weak_ptr_test.cc \
   $$PWD/tests/unit/websocket_test.cc

INCLUDEPATH = \
    $$PWD/build/debug/gen/src/proto \
    $$PWD/build/release/gen/src/proto \
    $$PWD/build2/gen/src/proto

#DEFINES = 

