client:
  nodelay: # bool, whether or not to set tcp_nodelay option
server:
  nodelay: # bool, whether or not to set tcp_nodelay option
jobs:
  - name: # any parseable string
    type: rpc
    verb: # string, one of: echo, vecho, write
    parallelism: # number of verbs to send simultaneously
    shares: # sched group shares (100 by default)
    payload: # number of bytes in the payload for write verb, accepts kB suffix
    sleep_time: # optional inactivity pause between sending messages
    timeout: # optional rpc send timeout duration
  - name: # any parseable string
    type: rpc_streaming
    verb: # string, one of: bidirectional, unidirectional
           # - bidirectional: client sends payload_t, server responds asynchronously with received data
           # - unidirectional: client sends payload_t, server consumes without responding
    parallelism: # number of streaming workers to run simultaneously
    shares: # sched group shares (100 by default)
    payload: # number of bytes in the payload sent from client to server, accepts kB suffix
    sleep_time: # optional inactivity pause between sending messages
  - name:
    type: cpu
    execution_time: # time in [0-9]+[mun]?s format
    sleep_time: # optional inactivity pause between burning cpu
    side: # optional, 'client' or 'server' to specify which side to run on
