#!/usr/bin/env -S uv run --script
#
# This file is open source software, licensed to you under the terms
# of the Apache License, Version 2.0 (the "License").  See the NOTICE file
# distributed with this work for additional information regarding copyright
# ownership.  You may not use this file except in compliance with the License.
#
# You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
#
# Copyright (C) 2026 Redpanda Data.
#
# /// script
# requires-python = ">=3.10"
# dependencies = [
#   "allpairspy",
#   "ruamel.yaml",
# ]
# ///
"""
Generate the regular_test include: matrix for tests.yaml.

Uses all-pairs (pairwise) coverage over compiler x standard x mode x
arch for the regular builds, plus an explicit list of special-purpose
jobs (dpdk, cxx-modules, fuzz). All-pairs guarantees that every pair
of parameter values is exercised by at least one job, with far fewer
combinations than the full cartesian product. Excluded pairs (see
EXCLUDED_PAIRS) drop out of regular coverage. The file is round-tripped
through ruamel.yaml, replacing only the strategy matrix include list;
everything else in tests.yaml is left untouched.

Usage:
    .github/workflows/gen-matrix.py
    git diff .github/workflows/tests.yaml
"""

import pathlib
from typing import Any

from allpairspy import AllPairs
from ruamel.yaml import YAML
from ruamel.yaml.comments import CommentedMap, CommentedSeq

HERE = pathlib.Path(__file__).parent
TESTS_YAML = HERE / "tests.yaml"

# Compilers are named with the version suffix that matches the Ubuntu
# package binary (clang-21, g++-16, ...). install-build-env.sh installs
# the corresponding apt package and derives CC from CPP. We cover the
# last two major releases of each toolchain per compatibility.md.
CLANG_VERSIONS: list[int] = [21, 22]
GCC_VERSIONS:   list[int] = [15, 16]
COMPILERS: list[str] = (
    [f"clang++-{v}" for v in CLANG_VERSIONS]
    + [f"g++-{v}"   for v in GCC_VERSIONS]
)
STANDARDS: list[int] = [23, 26]
MODES: list[str] = ["debug", "release", "sanitize"]
ARCHS: list[str] = ["x86", "arm"]

# Compiler+mode combinations to skip in the regular all-pairs matrix.
# gcc 15+ miscompiles structured bindings inside loops in coroutines
# (https://gcc.gnu.org/bugzilla/show_bug.cgi?id=124584), breaking g++
# debug (LSan: pollable_fd_state leak via cross-shard accept) and g++
# sanitize (UBSan abort on poisoned rcv_buf in rpc loops). Tracked in
# scylladb/seastar#3431.
EXCLUDED_PAIRS: list[tuple[str, str]] = [
    (f"g++-{v}", m) for v in GCC_VERSIONS for m in ("debug", "sanitize")
]


def _keep_row(row: list[Any]) -> bool:
    """allpairspy filter_func: drop rows hitting an EXCLUDED_PAIRS entry.

    Called with progressively longer prefixes during pair generation, so
    the check only fires once both compiler (row[0]) and mode (row[2])
    are present in the partial row.
    """
    return not (len(row) >= 3 and (row[0], row[2]) in EXCLUDED_PAIRS)

# Key path to the strategy matrix map inside tests.yaml; we replace its
# "include" list. The "# AUTOGENERATED" comment is preserved automatically
# on round-trip.
MATRIX_PATH = ("jobs", "regular_test", "strategy", "matrix")

# Special jobs merged into the same matrix so tests.yaml stays a single job.
# Items only set enable-ccache when overriding the default (test.yaml treats
# absent/empty as enabled).
SPECIAL_ITEMS: list[dict[str, Any]] = [
    {
        "compiler": "clang++-22",
        "standard": 23,
        "arch": "x86",
        "mode": "dev",
    },
    {
        "compiler": "clang++-22",
        "standard": 23,
        "arch": "x86",
        "mode": "release",
        "enables": "--enable-dpdk",
        "options": "--cook dpdk --dpdk-machine corei7-avx",
        "info": "dpdk, ",
    },
    {
        "compiler": "clang++-22",
        "standard": 23,
        "arch": "x86",
        "mode": "debug",
        "enables": "--enable-cxx-modules",
        "enable-ccache": False,
        "info": "modules, ",
    },
    {
        "compiler": "clang++-22",
        "standard": 23,
        "arch": "x86",
        "mode": "fuzz",
        "test-args": "-- -R 'Seastar.fuzz.'",
    },
]

def _build_include(items: list[dict[str, Any]]) -> CommentedSeq:
    """Build the matrix include list as a block sequence of flow mappings.

    Each item becomes a flow-style mapping (one job per line) so the block
    stays compact and diff-friendly; ruamel.yaml handles scalar quoting.
    """
    seq = CommentedSeq()
    for item in items:
        mapping = CommentedMap(item)
        mapping.fa.set_flow_style()
        seq.append(mapping)
    return seq


def generate() -> list[dict[str, Any]]:
    regular: list[dict[str, Any]] = [
        {"compiler": c, "standard": s, "mode": m, "arch": a}
        for c, s, m, a in AllPairs(
            [COMPILERS, STANDARDS, MODES, ARCHS],
            filter_func=_keep_row,
        )
    ]
    return regular + SPECIAL_ITEMS


def main() -> None:
    items = generate()

    yaml = YAML()
    yaml.preserve_quotes = True
    yaml.width = 1 << 20  # never wrap a flow mapping across lines
    yaml.indent(mapping=2, sequence=4, offset=2)

    data = yaml.load(TESTS_YAML)
    matrix = data
    for key in MATRIX_PATH:
        matrix = matrix[key]

    # We only swap out the include list. The "# AUTOGENERATED, do not edit"
    # comment is attached to the include key, not the list, so it is
    # preserved automatically on round-trip.
    matrix["include"] = _build_include(items)

    yaml.dump(data, TESTS_YAML)
    print(f"Updated {TESTS_YAML}: {len(items)} matrix items")


if __name__ == "__main__":
    main()
