#!/usr/bin/env python3
"""
Generate the regular_test include: matrix for tests.yaml.

Computes the Cartesian product of compilers × standards × modes for
regular builds, then appends special-purpose jobs (dpdk, cxx-modules,
fuzz) so that tests.yaml has a single job definition for all of them.
Everything outside the marked region is left untouched.

Usage:
    python3 .github/workflows/gen-matrix.py
    git diff .github/workflows/tests.yaml
"""

import itertools
import pathlib
from typing import Any

HERE = pathlib.Path(__file__).parent
TESTS_YAML = HERE / "tests.yaml"

# Compilers are named with the version suffix that matches the Ubuntu
# package binary (clang-21, g++-16, ...). install-build-env.sh installs
# the corresponding apt package and derives CC from CPP. We cover the
# last two major releases of each toolchain per compatibility.md.
CLANG_VERSIONS: list[int] = [21, 22]
GCC_VERSIONS:   list[int] = [15, 16]
COMPILERS: list[str] = (
    [f"clang++-{v}" for v in CLANG_VERSIONS]
    + [f"g++-{v}"   for v in GCC_VERSIONS]
)
STANDARDS: list[int] = [20, 23]
MODES: list[str] = ["dev", "debug", "release"]

# Markers that bracket the managed region inside tests.yaml.
BEGIN_TAG = "# This include block is AUTOGENERATED"
END_TAG = "# end of AUTOGENERATED part"

# Special jobs merged into the same matrix so tests.yaml stays a single job.
# Items only set enable-ccache when overriding the default (test.yaml treats
# absent/empty as enabled).
SPECIAL_ITEMS: list[dict[str, Any]] = [
    {
        "compiler": "clang++-22",
        "standard": 23,
        "mode": "release",
        "enables": "--enable-dpdk",
        "options": "--cook dpdk --dpdk-machine corei7-avx",
        "info": "dpdk, ",
    },
    {
        "compiler": "clang++-22",
        "standard": 23,
        "mode": "debug",
        "enables": "--enable-cxx-modules",
        "enable-ccache": False,
        "info": "modules, ",
    },
    {
        "compiler": "clang++-22",
        "standard": 23,
        "mode": "fuzz",
        "test-args": "-- -R 'Seastar.fuzz.'",
    },
]

# Characters that require a value to be double-quoted in YAML flow style.
_NEEDS_QUOTE: frozenset[str] = frozenset(' ,:{}"[]#')


def _yaml_val(v: object) -> str:
    if isinstance(v, bool):
        return "true" if v else "false"
    if isinstance(v, int):
        return str(v)
    s = str(v)
    if any(c in s for c in _NEEDS_QUOTE):
        return '"' + s.replace("\\", "\\\\").replace('"', '\\"') + '"'
    return s


def _format_item(item: dict[str, Any], indent: str) -> str:
    parts = ", ".join(f"{k}: {_yaml_val(v)}" for k, v in item.items())
    return f"{indent}  - {{{parts}}}\n"


def generate() -> list[dict[str, Any]]:
    regular: list[dict[str, Any]] = [
        {"compiler": c, "standard": s, "mode": m}
        for c, s, m in itertools.product(COMPILERS, STANDARDS, MODES)
    ]
    return regular + SPECIAL_ITEMS


def main() -> None:
    items = generate()
    lines: list[str] = TESTS_YAML.read_text().splitlines(keepends=True)

    begin_idx = next(i for i, line in enumerate(lines) if BEGIN_TAG in line)
    end_idx   = next(i for i, line in enumerate(lines) if END_TAG   in line)

    first = lines[begin_idx]
    indent = " " * (len(first) - len(first.lstrip()))

    new_lines: list[str] = [
        f"{indent}{BEGIN_TAG}, do not edit by hand\n",
        f"{indent}# instead edit + re-run .github/workflows/gen-matrix.py\n",
        f"{indent}include:\n",
    ]
    for item in items:
        new_lines.append(_format_item(item, indent))

    TESTS_YAML.write_text("".join(lines[:begin_idx] + new_lines + lines[end_idx:]))
    print(f"Updated {TESTS_YAML}: {len(items)} matrix items")


if __name__ == "__main__":
    main()
